# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 17:14
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def forwards_func(apps, schema_editor):
    call_command('sync_page_translation_fields', '--noinput')


def reverse_func(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
