version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pivhhupdpzootr
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django
    volumes:
      - ./.db:/docker-entrypoint-initdb.d
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=durhamforall.settings.dev-docker
      - DJANGO_LOG_LEVEL=WARNING
      - SECRET_KEY=testt
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - AWS_STORAGE_BUCKET_NAME=durhamforall-web
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
