
version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pivhhupdpzootr
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django
    volumes:
      - ./.db:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
  vendors:
    image: python:3
    working_dir: /mnt
    volumes:
       - .:/mnt
    environment:
      - PYTHONUSERBASE=/mnt/vendor
    command: pip install -r requirements.txt --user --upgrade
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mnt
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=durhamforall.settings.dev-docker
      - DJANGO_LOG_LEVEL=WARNING
      - SECRET_KEY=testt
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - AWS_STORAGE_BUCKET_NAME=durhamforall-web
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PYTHONUSERBASE=/mnt/vendor
