version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pivhhupdpzootr
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django
    volumes:
      - ./.db:/docker-entrypoint-initdb.d
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=durhamforall.settings.dev-docker
      - SECRET_KEY=testt
