# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('blog', '0005_auto_20171203_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro_en',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro_es',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
